name: movie_app_with_clean_arch
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  dio:
  dartz:
  flutter_bloc:
  get_it:
  shimmer:
  animate_do:
  cached_network_image:
  carousel_slider:
  intl: ^0.19.0
  lottie:
  google_fonts: ^4.0.5
  youtube_player_iframe: ^4.0.4
  hive: ^2.2.3
  hive_flutter:
  path_provider:
  flutter_native_splash:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/lottie/
