// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvvwdTyiRJ7wx9kMvBpi8dCd_jDjFdP3k',
    appId: '1:59935847939:web:7f76101818b5e9cefbc036',
    messagingSenderId: '59935847939',
    projectId: 'filmfy-609c1',
    authDomain: 'filmfy-609c1.firebaseapp.com',
    storageBucket: 'filmfy-609c1.appspot.com',
    measurementId: 'G-TY8HZR0SH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCct_yq7g3ftqmA9sMr_m0JdJfoMULjqSg',
    appId: '1:59935847939:android:8522891e81641c6ffbc036',
    messagingSenderId: '59935847939',
    projectId: 'filmfy-609c1',
    storageBucket: 'filmfy-609c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYpZ0EI9-R0N6I8Y1bs7IhRwwy_KEOgKA',
    appId: '1:59935847939:ios:c5c48bd71391c50efbc036',
    messagingSenderId: '59935847939',
    projectId: 'filmfy-609c1',
    storageBucket: 'filmfy-609c1.appspot.com',
    iosBundleId: 'com.example.movieAppWithCleanArch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYpZ0EI9-R0N6I8Y1bs7IhRwwy_KEOgKA',
    appId: '1:59935847939:ios:c5c48bd71391c50efbc036',
    messagingSenderId: '59935847939',
    projectId: 'filmfy-609c1',
    storageBucket: 'filmfy-609c1.appspot.com',
    iosBundleId: 'com.example.movieAppWithCleanArch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvvwdTyiRJ7wx9kMvBpi8dCd_jDjFdP3k',
    appId: '1:59935847939:web:645db2af4854c82ffbc036',
    messagingSenderId: '59935847939',
    projectId: 'filmfy-609c1',
    authDomain: 'filmfy-609c1.firebaseapp.com',
    storageBucket: 'filmfy-609c1.appspot.com',
    measurementId: 'G-1E8BG2Q18B',
  );
}
